### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by eraycetinay**

### CODE REVIEW

**Comment by thedaviddias** [comment]
Hi @eraycetinay, that could be great if you find a way to have just only one repository and work together with the other developer 😉

**Comment by eraycetinay** [comment]
@thedaviddias; i have sent an email to @erdoganoksuz and my translation is already done.  i was started it one and half week ago. He has translated a few paragraphs yet. it may make more sense to cancel it. But I still can not get any response from him.

**Comment by thedaviddias** [comment]
Ok, you may be more motivated :) Soon, you'll need to update some JSON files to generate the app in Turkish too :) I just need some rework to enable the translation.

**Comment by eraycetinay** [comment]
Sure, i will be waiting.

**Comment by eraycetinay** [comment]
@thedaviddias;  
@erdoganoksu says he wants to continue his translate. But he could only translate on weekends.
at this point, one title has been translated yet. so i recommend removing his repo's link from readme.md file until the translation is completed by him.

**Pull request merged**
