### PR TITLE
Link page amp

### PR DESCRIPTION
**Pull request by torresgol10**
**Fixes**: #

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

#### Proposed changes:

- Link Page AMP
-
-

👍 Thank you!

### CODE REVIEW

**Comment by torresgol10** [comment]
I set the priority to low?

**Comment by thedaviddias** [comment]
Yes please.

**Comment by patrick-mcdougle** [comment]
I don't think this should be in here at all. AMP is not for your website, it's a secondary content platform that augments (competes with?) the web.

**Comment by torresgol10** [comment]
If you do a google search from a mobile, you will always be offered a page with AMP technology, then directly influences the web.

**Comment by thedaviddias** [comment]
I'm closing that issue for now and will probably review if AMP should be in the next version of the FEC soon.

**Pull request closed without merging**
