### PR TITLE
Noted TinyPNG isn't lossless

### PR DESCRIPTION
**Pull request by angleKH**
On the site, it says that the compression is lossy, not lossless.

### CODE REVIEW

**Comment by angleKH** [comment]
Here is a comment to avoid the bot from removing it.

**Comment by angleKH** [comment]
Here is some more noise, courtesy of stale bot.

**Comment by angleKH** [comment]
Another temporary noise comment for the bot

**Comment by angleKH** [comment]
TinyPNG is not lossless (and this is even stated on their site), so the current text is misleading, it could lead someone to use it thinking it's lossless when it isn't.

**Comment by angleKH** [comment]
@thedaviddias, can you merge this or provide a comment?

**Review by coliff — APPROVED** [review]

**Review by thedaviddias — APPROVED** [review]

**Comment by thedaviddias** [comment]
It's never too late 😅

**Comment by thedaviddias** [comment]
@angleKH sorry for the immense delay, now merged 😉

**Pull request merged**
