### PR TITLE
Google officially increases length of snippets in search results

### PR DESCRIPTION
**Pull request by DarekRomanowski**
Google officially increases length of snippets in search results

**Fixes**: 

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:

Meta Description length has grown from 160 characters to almost 230 characters on average.

#### Proposed changes:

-
-
-

👍 Thank you!

### CODE REVIEW

**Comment by DarekRomanowski** [comment]
Ive fixed my commit :) I hope its good now :)

**Comment by thedaviddias** [comment]
Hi @DarekRomanowski, at the end of the article, they seem to say that is not a good thing to change now... I agree that for now, it's better to not make that change... What do you think?

**Comment by thedaviddias** [comment]
Hi @DarekRomanowski, any feedback?

**Comment by jeffreyrufino** [comment]
Great Job David!

**Pull request closed without merging**
