### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by schbz**
changed "rich restults test" to "rich results test"

**Fixes**: #

🚨 Please review the [guidelines for contributing](CONTRIBUTING.md) and our [code of conduct](../CODE_OF_CONDUCT.md) to this repository. 🚨
**Please complete these steps and check these boxes (by putting an x inside the brackets) before filing your PR:**

- [ x] Check the commit's or even all commits' message styles matches our requested structure.
- [ x] Check your code additions will fail neither code linting checks nor unit test.

#### Short description of what this resolves:
the word "results" was misspelled. 

#### Proposed changes:
just a simple typo correction. Everything else looks perfect.
-
-
-

👍 Thank you!

### CODE REVIEW

**Comment by 9ebd7134** [comment]
no one cares about a typo :) Thanks

**Comment by schbz** [comment]
> no one cares about a typo :) Thanks

True, I've got to start somewhere though, lol

**Comment by 9ebd7134** [comment]
> > no one cares about a typo :) Thanks
> 
> True, I've got to start somewhere though, lol

You start by helping people, not fixing a typo. Btw if your reading this you prob read typo's like they are correct. Sad to see people get credit for fixing a typo.

**Comment by schbz** [comment]
there's a big dif between typos and abbrv. if you don't want to give me credit then don't. I was just experimenting with the pull request system.

**Comment by 9ebd7134** [comment]
Experiment on your own repo's.

**Comment by 9ebd7134** [comment]
I'm not trying to be rude.
I'm just saying "Stop opening a pull for a simple typo"
That's all.

Regards,
Stay safe,
Ryan s.

**Comment by schbz** [comment]
message received. Now I know. have a nice day.

**Comment by 9ebd7134** [comment]
> message received. Now I know. have a nice day.

sorry to be a pain in the ass. Just tryin to remove bad habits with people fixing typo's in like every repository

**Comment by schbz** [comment]
> > message received. Now I know. have a nice day.
> 
> sorry to be a pain in the ass. Just tryin to remove bad habits with people fixing typo's in like every repository

No worries. I wouldn't want people spamming my repos either. For future reference, is it a good idea to open an issue to notify people of things like spelling mistakes instead, or is it more polite to just completely ignore them?

**Comment by clovergaze** [comment]
Seriously, if you want to improve something, go ahead and do as you please. I like reading stuff without typos in it.

**Comment by 9ebd7134** [comment]
> > > message received. Now I know. have a nice day.
> > 
> > 
> > sorry to be a pain in the ass. Just tryin to remove bad habits with people fixing typo's in like every repository
> 
> No worries. I wouldn't want people spamming my repos either. For future reference, is it a good idea to open an issue to notify people of things like spelling mistakes instead, or is it more polite to just completely ignore them?

i rlly would say you can ignore them. But i dont know why you closed this pull. I didn't tell you to remove it i just told you that it can be quite annoying :) 

i'd be happy if you re-opened this

**Comment by schbz** [comment]
Ok cool thanks.

**Comment by thedaviddias** [comment]
> Ok cool thanks.

I'm sorry @schbz to have not seen this conversation before, any contribution is valuable, thanks for fixing an issue even it's just a typo issue.

@9ebd7134 we have rules on Github and on this repo, respect is one of the rule, please avoid discouraging newcomers just trying to enter in the world of open-source. Anyone can starts with what they feel confortable.

**Pull request merged**
