### PR TITLE
Added Microsoft's browser configuration scheme

### PR DESCRIPTION
**Pull request by DylanTackoor**
Describes minimum needed to enable tiles for pinned sites on Windows through Microsoft browsers.

Read more @ [Browser configuration schema reference](https://msdn.microsoft.com/en-us/library/dn320426(v=vs.85).aspx)

### CODE REVIEW

**Comment by thedaviddias** [comment]
Hi @DylanTackoor, thank you for your PR. I hesitated to put these references before to publish the first version on Github. I agree to put it on a low priority, but do you think it's something that is really needed for most of the websites?

**Comment by wang8850** [comment]
pull request

**Comment by jochenkirstaetter** [comment]
Yes, I think so. It gives additional features to Windows users using IE and Edge. Similar to a manifest file to enhance the experience for Chrome and Android users.

**Comment by DylanTackoor** [comment]
Agree with jochenkirstaetter. It's useful for those using IE and/or Edge and is trivially small/easy to implement.

Do also agree that it should be low priority. A "totally optional" flag would probably suit it best but only saw "low".

**Comment by thedaviddias** [comment]
Thanks for you POV guys, don't worry @DylanTackoor, for now, it can stay "low". I'll probably improve that system soon.

**Pull request merged**
