### PR TITLE
Remove pixel perfection as recommendation

### PR DESCRIPTION
**Pull request by andy-hook**
Awesome job on such a comprehensive list!

I had one rather large problem with the use of pixel perfect as a recommendation. With the proliferation of mobile devices and constant drive upwards in screen density I feel as a highly recommended practice this should be actively discouraged.

Now more than ever we are building systems of components that work together within the constraints of this large device landscape. Having this on the list sends the wrong message that it's acceptable without the context of the whole system. We should actively discourage the workflow in favour of close collaboration and education with designers less familiar with our front-end challenges. Often small discrepancies between mock and prod are due to needed compromise and aim to make the design stronger / more maintainable in the long term.

Falling down the rabbit hole of pixel nudging at arbitrary resolutions will only compromise the overall integrity of a system.

Just my 2c, thanks again for the work you have put in here.

### CODE REVIEW

**Comment by thedaviddias** [comment]
Hi @andy-hook, thank you for sharing your POV. I totally agree with you as "pixel perfect" is not how today, design and internet works.

I've been recently building a design system on Sketch for a big platform and since years, I'm the defensor of systems of components (Atomic Design etc).

Now, the issue is regarding some companies and professionals who work with QA teams. They, most of the time, compare what was done on the creative part and what was integrated in a final version. And with that tool they can say if the Front-End dev didn't integrate correctly the creatives.

This is why I put that reference...

**Comment by wang8850** [comment]
pull request

**Comment by wang8850** [comment]
pull request

**Comment by andy-hook** [comment]
I would say it was the job of the designer to submit revised designs to QA based on the compromises in that case. But I see your points for this inclusion. Perhaps a middle road is a listing for "Implementation signed off with designer" and a link to collaboration tools but again I don't know how useful this is as a recommendation. Either way I think this PR is valid if you agree.

Many thanks.

**Comment by thedaviddias** [comment]
@andy-hook Let's see what I can find to fit the middle term. I'm leaving the pull request open until I find some ideas about that. I'll share with you. Thanks!

**Comment by thedaviddias** [comment]
@geosenna Do you have some ideas on the subject?

**Comment by geosenna** [comment]
I am agree with the two ideas... Still my opinion is to let it in the list with a Low priority. 

Because this tool can be very useful in some cases for some developers. And for those who don't need it, they can just ignore it. This is the developer responsibility to chose either or not this tool is appropriate to its project.

**Comment by MrSunshyne** [comment]
I think this can be dealt with the following way : 

1. Pixel perfection as a concept is not how we do modern web design anymore. 
2. If you still want pixel perfection, the chrome extension `perfectpixel` is the right tool.

This is an interesting case where the community cannot really dictate the priority level of the feature. This one depends on the project owner. Hence LOW / MEDIUM / HIGH or even recommended do not apply here. 

I'd suggest adding another flag for things like this. The flag being : **[ Project Specific ]** or something similar

**Comment by thedaviddias** [comment]
Hey guys, thanks for your POV.

@andy-hook what do you think about maybe having another flag / image?

**Comment by mattfromseattle** [comment]
Agreed with @MrSunshyne that pixel perfect is something that's great in theory, but in the real world is difficult to obtain. Given the sheer number of devices and screen sizes out in the wild, something will always slip through the cracks or in some cases, cause other issues to address. That said, we should still strive to get as close as possible.

**Comment by andy-hook** [comment]
I also agree with @MrSunshyne - The current priority tags don't work in this instance as it's not a recommended practice. I do think there is value in having an entry for "Design sign off" and perhaps list this tool as useful in specific instances but focus primarily around collaboration in a modern digital design process.

**Comment by elliottregan** [comment]
I also agree with @MrSunshyne. 

I'd like to add, though, there are cases where certain CSS techniques can lead to non-pixel-perfect rendering of elements that would otherwise be "perfect", particularly text. A link to a list of common issues or techniques that lead to those issues could be added to keep this tip actionable, and project-agnostic.

For example, using CSS transforms to align elements vertically can lead to blurry text if the pixel-rounding isn't discrete. An issue like 'blurry text due to CSS' could apply to any website, regardless of creative direction or workflow.

**Comment by okcoker** [comment]
I would put this as Low Priority. On first thought I was going to agree with @MrSunshyne about making it **[Project Specific]** but if we are considering responsive design a high priority (which I do agree with), then this point becomes less important. Usually in my experience the flow goes:

> Designer: Make this
> 
> Dev: Makes that
> 
> Designer: This is a little off can we move this around
> 
> Dev: Moves around to be perfect
> 
> Designer: This is a little off on my phone
> 
> Dev: Adds media query
> 
> Designer: This is a little off on my phone in landscape mode
> 
> Dev: Adds height related media query
> 
> Designer: This is a litte off on my ipad
> 
> Dev: Adds media query
> 
> Designer: This is a little off again on my 13 inch macbook
> 
> Dev: Adds another media query while thinking the designer should learn css
> 
> etc etc

I don't think it makes sense to think in absolute units anymore and it hasn't for a while. It's more about max and min units which means the designer should be more aware of these New Rules ™ when building. It causes more bloat in your CSS files which ultimately could hurt performance. Sometimes it ends up being that you just make things pixel perfect for whatever device that person owns but we all know that doesn't cover everything. IMO its much better to cover the main breakpoints for which you get traffic on (which is mentioned in this checklist already) and gracefully handle, and sometimes just be ok with, anything after that. Or simply add a breakpoint whenever your design starts to degrade.

**Comment by thedaviddias** [comment]
Hey guys, can you take a look on my proposal d9a4172? I changed from *Pixel Perfect* to *Design fidelity*... That could be a way to tackle that...

**Comment by thedaviddias** [comment]
@andy-hook @MrSunshyne @elliottregan can you take a look on my proposal d9a4172? I changed from Pixel Perfect to Design fidelity... That could be a way to tackle that...

**Pull request closed without merging**
