### PR TITLE
 The Chinese version

### PR DESCRIPTION
**Pull request by JohnsenZhou**

### CODE REVIEW

**Comment by thedaviddias** [comment]
Hi @JohnsenZhou, you PR is not valid, you are trying to change the Front-End Checklist which is in English in Chinese.

I think you made a mistake as I saw you are working on a Chinese version...

Can you explain?

**Comment by thedaviddias** [comment]
@JohnsenZhou, I still don't understand what you are trying to do. Please explain.

**Comment by JohnsenZhou** [comment]
@thedaviddias sorry,I open a invalid PR.I'll close it.

**Comment by thedaviddias** [comment]
Thanks!

**Pull request closed without merging**
