### PR TITLE
Add prefetching techniques in performance section

### PR DESCRIPTION
**Pull request by antarestupin**
Hello,

I've created [this checklist](https://github.com/antarestupin/performance-checklist) focused on performance recently and I'd like to share some practices that I don't see yet in this list.

I wanted to begin with techniques allowing to prepare upcoming requests during browser's idle time, so I'm adapting [this section](https://github.com/antarestupin/performance-checklist#prepare-next-requests) to the format used here.

I've created a sub-section in `Performance`, but I'm not sure of where this section should be placed as there are performance related practices spread over all the list, so it's open to discussion. Same for the levels of flexibility.

### CODE REVIEW

**Comment by brunah** [comment]
Quero decriptar minhas conversas

**Comment by brunah** [comment]
Eu criei uma sub-seção Performance, mas não tenho certeza de onde esta seção deve ser colocada, pois há práticas relacionadas ao desempenho espalhadas por toda a lista, por isso está aberto a discussão. Mesmo para os níveis de flexibilidade.

**Comment by wang8850** [comment]
Good

**Comment by thedaviddias** [comment]
Hi @antarestupin, thank you so much for the addition. I wanted to put these too, I think they are important. At the same time, I agree to keep it on low priority.

It could be interesting to link to another articles or documentation and have an explanation accessible for beginners.

For the section, let's keep it that way for now and see later where could be the best place on the checklist. 😉

**Comment by wang8850** [comment]
pull request

**Pull request merged**
